### ISSUE TITLE
小白请教：请问url封装到了哪里？

### ISSUE THREAD

**Issue by ghost** [chkfung/MeizhiGank#2]
我在NetworkApi接口中看到了@GET("api/data/福利/{amount}/{page}")
没有找到前缀"gank.io"，不知道是被封装到了哪里？

抱歉，打扰了。已经解决。。

**Comment by chkfung** [comment]
在这里, [NetModule](https://github.com/chkfung/MeizhiGank/blob/master/app/src/main/java/me/chkfung/meizhigank/Dagger/Module/NetModule.java)
