### ISSUE TITLE
请问googleplay上这个应用是您开发的吗 

### ISSUE THREAD

**Issue by specloli** [chkfung/MeizhiGank#3]
https://play.google.com/store/apps/details?id=me.strugglingvincent.meizhigank 
这是谷歌商店的地址，因为我想找应用源码所以根据开发者strugglingvincent@gmail.com找到了strugglingvincent1008这个用户，然后看到了您的代码，但是您那个谷歌play的链接不能访问，而且包名也不一样，所以我想问一句 ，请问这个应用是谁开发的？如果您是源作者，而应用商店不是您的应用，请谴责这种盗取源码并用于个人获取商业利益的行为，另外请在源码上注明您所使用的开源协议，一起保护开源世界。

**Comment by chkfung** [comment]
感谢通知！
前不久Google play 把这个App连同很多大神的Gank客户端也一起下架了，所以链接失效了。
已经举报了，一起保护开源世界，谢谢！
